#!/bin/bash

# Flutter Performance Profiling Guide

echo "======================================"
echo "Flutter Performance Profiling Guide"
echo "======================================"
echo ""
echo "Step 1: Start the app in PROFILE mode (not debug)"
echo "$ flutter run --profile"
echo ""
echo "Step 2: Open DevTools in a new terminal"
echo "$ flutter pub global run devtools"
echo ""
echo "Step 3: Connect to the running app"
echo "- DevTools will open at http://localhost:9100"
echo "- Select your device from the dropdown"
echo ""
echo "Step 4: Capture a timeline trace"
echo "- Click on the 'Timeline' tab"
echo "- Click the 'Record' button"
echo "- Tap on a transaction in your app"
echo "- Wait for the action to complete"
echo "- Click 'Stop' to end the recording"
echo ""
echo "Step 5: Analyze the trace"
echo "- Look for frames that take > 16.6ms (60fps)"
echo "- Look for yellow/red bars indicating slow work"
echo "- Check the 'Build' and 'Layout' times"
echo ""
echo "Common causes of lag:"
echo "- Expensive widget builds (look for wide bars)"
echo "- Layout thrashing (look for many Layout events)"
echo "- Garbage collection pauses"
echo "- Unoptimized animations"
echo ""
echo "Profile mode has ~10x less overhead than debug mode"
echo "This will show you the REAL performance characteristics"
echo ""
